"""
NoetherCurrents — Forward and Backward, from one symmetry.

The same Noether armature generates both:

  Forward current  (Riemann / Red):  what the word IS.
                                      The attractor. The equator. What settles.
                                      L_R = ẋ log ẋ − ẋ

  Backward current (Fermat  / Blue): what the word CANNOT BE.
                                      The repulsor. The forbidden zone. What cannot settle.
                                      L_F = the Frey elliptic Lagrangian

The rotating field (Phase 3 / Yang-Mills) is their interaction.
The word is where forward and backward agree.

Electrons travel one way. Charge travels the other. Same wire.
"""

from math import log
from .hamiltonian import HamiltonianXP
from .semantic_word import SemanticWord


class NoetherCurrents:
    """
    The two Noether currents generated by the symmetry of the semantic Lagrangian.

    Forward  (Red):  ∂L_R/∂(∂φ) — conserved along the attractor geodesic
    Backward (Blue): ∂L_F/∂(∂φ) — conserved along the repulsor geodesic

    Their balance is the prime.
    """

    def __init__(self):
        self._H = HamiltonianXP()

    def forward(self, word: SemanticWord, t: float = 1.0) -> float:
        """
        Forward Noether current.
        Evolve the word forward along H = xp.
        The current is the rate of change of the semantic prime.

        J_forward = x · ∂L/∂ẋ − L = E (the conserved prime itself)
        """
        x0 = abs(word.prime) if word.prime != 0 else 1.0
        p0 = 1.0 / x0 if x0 != 0 else 1.0
        x, p = self._H.trajectory(x0, p0, t)
        current = self._H.prime(x, p)
        word.noether_forward = current
        return current

    def backward(self, word: SemanticWord, t: float = 1.0) -> float:
        """
        Backward Information Current.
        The Fermat constraint: what cannot settle here.
        Run the Lagrangian in reverse — the inverse direction.

        The backward current is the forward current reflected:
        J_backward = −J_forward evaluated at the boundary.
        Where J_forward + J_backward = 0: the equator. The prime.
        """
        fwd = word.noether_forward if word.noether_forward != 0 else self.forward(word, t)
        current = -fwd
        word.noether_backward = current
        return current

    def rotating_field(self, word: SemanticWord) -> float:
        """
        Phase 3 — the Yang-Mills carrier.
        The rotating semantic field: the interaction of forward and backward.
        This is the meaning. Not forward. Not backward. Their rotation.

        J_3 = (J_forward − J_backward) / 2
        """
        fwd = word.noether_forward
        bwd = word.noether_backward
        field = (fwd - bwd) / 2.0
        return field

    def balance(self, word: SemanticWord) -> float:
        """
        Where forward and backward agree: the prime.
        J_forward + J_backward + J_3 = 0  (three-phase balance)
        """
        self.forward(word)
        self.backward(word)
        f3 = self.rotating_field(word)
        total = word.noether_forward + word.noether_backward + f3
        return total

    def forced_sigma(self, E: float, sigma_0: float = 0.0) -> float:
        """
        The mathematics forces the observer to sigma = 1/2.
        Not assigned. Derived.

        From the right (σ > 1/2): forward current  F(σ) = e^{-σ·E}
        From the left  (σ < 1/2): backward current B(σ) = e^{-(1-σ)·E}

        They meet where F(σ) = B(σ):
            e^{-σE} = e^{-(1-σ)E}
            σ = 1 - σ
            σ = 1/2

        From ANY starting position. From opposite sides.
        The radial spherical complex polar geometry forces the meeting point.
        """
        from math import exp
        sigma = sigma_0
        for _ in range(2048):
            F = exp(-sigma * E)           # forward: from the right
            B = exp(-(1.0 - sigma) * E)   # backward: from the left
            if F + B < 1e-30:
                break
            sigma_new = (F * sigma + B * (1.0 - sigma)) / (F + B)
            if abs(sigma_new - sigma) < 1e-12:
                break
            sigma = sigma_new
        return sigma   # always 0.5
